# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'MapMagicPractice' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

     # Flexbox Layout Manager Used By React Natve
   pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga/Yoga.podspec'
  
   # React Native
   pod 'React', path: '../node_modules/react-native', subspecs: [
     # Comment out any unneeded subspecs to reduce bundle size.
     'Core',
     'DevSupport',
     'RCTAnimation',
     'RCTBlob',
     'RCTGeolocation',
     'RCTImage',
     'RCTNetwork',
     'RCTSettings',
     'RCTTest',
     'RCTText',
     'RCTWebSocket',
     'RCTLinkingIOS'
   ]
 
   # Mapbox
   pod 'react-native-mapbox-gl', :path => '../node_modules/react-native-mapmagic-gl'

  target 'MapMagicPracticeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'MapMagicPractice-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MapMagicPractice-tvOS

  target 'MapMagicPractice-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
